name: Package Application with Pyinstaller

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        run: pip install pyinstaller

      - name: Build
        run: pyinstaller --onefile --noconsole PySender\__main__.py

      - uses: actions/upload-artifact@v2
        with:
          name: PySender
          path: ./dist