name: Manual PyPi Release

on:
  release:
    types: [created]

env:
  PYTHON_VERSION: '3.10.0'

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Change Version
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          echo "__version__ = '$VERSION'" > ./PySender/__version__.py
      - name: Install pypa/build
        run: |
          pip install pyqt5 requests twine
          pip install build
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
  publish:
    name: Publish on TestPyPi
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: dist
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
