name: Manual PyPi Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

env:
  PYTHON_VERSION: '3.10.0'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Change Version
        run: echo "__version__ = '${{ github.event.inputs.tag }}'" > PySender/__version__.py
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pypa/build
        run: |
          pip install pyqt5 requests
          pip install build
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
  publish:
    name: Publish on TestPyPi
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
