name: Upload Python App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
        python setup.py install
        
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY: testpypi
